%BP_RECTAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 05-Jun-2019 13:43:16

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 25;       % Order
Fc1  = 0.45;      % First Cutoff Frequency
Fc2  = 0.55;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
b2  = fir1(N, [Fc1 Fc2], 'bandpass', win, flag);
Hd = dfilt.dffir(b2);

[hf2,wf2]=freqz(b2,1,512);
% figure('Name','Filter of hp');
% plot(wf2,abs(hf2));
% [EOF]
