%HP_RACTAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 05-Jun-2019 13:32:21

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 25;       % Order
Fc   = 0.8;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
b3  = fir1(N, Fc, 'high', win, flag, 'h');
Hd = dfilt.dffir(b3);

[hf3,wf3]=freqz(b3,1,512);
% figure('Name','Filter of bp');
% plot(wf3,abs(hf3));
% [EOF]
