%BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 05-Jun-2019 13:10:06

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 25;       % Order
Fc1  = 0.4;      % First Cutoff Frequency
Fc2  = 0.6;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2], 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
