%LP_RECTAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 05-Jun-2019 13:26:04

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 25;       % Order
Fc   = 0.3;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
b1  = fir1(N, Fc, 'low', win, flag);
Hd = dfilt.dffir(b1);

[hf1,wf1]=freqz(b1,1,512);
% figure('Name','Filter of lp');
% plot(wf1,abs(hf1));
% [EOF]
